name: Check Changes and Tag

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  check-changes-and-tag:
    runs-on: ${{ inputs.runner }}

    steps:
      - name: Ensure Git and Github CLI is installed
        run: |
          sudo apt-get update
          sudo apt-get install -y git gh

      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history, including tags. Not good for large repos.
          token: ${{ secrets.token }}

      - name: Set up Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      # Step 1: Determine changes since the last tag
      - name: Check for changes
        id: check-changes
        run: |
          # Fetch all tags and determine if any changes have been made since the last tag
          git fetch --tags
          latest_tag=$(git describe --tags --abbrev=0)
          changes=$(git log $latest_tag..HEAD --oneline -- . ':!*.github/*')

          if [ -z "$changes" ]; then
            echo "No changes detected."
            echo "changes-detected=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          echo "Changes detected."
          echo "latest-tag=$latest_tag" >> $GITHUB_OUTPUT
          echo "changes-detected=true" >> $GITHUB_OUTPUT
          echo "changes=$changes" >> $GITHUB_OUTPUT

      - name: Determine new version
        if: steps.check-changes.outputs.changes-detected == 'true'
        id: version
        run: |
          # Get the latest tag and calculate the new version
          latest_tag="${{ steps.check-changes.outputs.latest-tag }}"
          tag_count=$(git tag -l | wc -l)

          if [ "$tag_count" -eq 0 ]; then
            echo "No tags found. Starting with 0.0.1"
            new_version="0.0.1"
          else
            # Extract major, minor, patch, and increment the patch
            IFS='.' read -r -a version_parts <<< "${latest_tag#v}"
            major=${version_parts[0]}
            minor=${version_parts[1]}
            patch=${version_parts[2]}
            patch=$((patch + 1))
            new_version="${major}.${minor}.${patch}"
          fi

          echo "new-version=$new_version" >> $GITHUB_OUTPUT

      - name: Update CHANGELOG.md
        if: steps.check-changes.outputs.changes-detected == 'true'
        id: update-changelog
        run: |
          new_changelog="## ${{ steps.version.outputs.new-version }}\n\n"            
          while IFS= read -r line; do
            new_changelog+="* $line\n"
          done <<< "${{ steps.check-changes.outputs.changes }}"

          # Prepend new changelog entry to the existing CHANGELOG.md
          echo -e "$new_changelog\n\n$(cat CHANGELOG.md)" > CHANGELOG.md

          # Commit the changelog update
          git add CHANGELOG.md
          git commit -m "Update changelog for ${{ steps.version.outputs.new-version }}"

          # Tag the commit with the new version
          git tag "${{ steps.version.outputs.new-version }}"

      - name: Create Pull Request
        if: steps.check-changes.outputs.changes-detected == 'true'
        id: create-pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.token }}
          branch: release-${{ steps.version.outputs.new-version }}
          base: main
          title: "Release ${{ steps.version.outputs.new-version }}"
          body: "This pull request contains the changes for release ${{ steps.version.outputs.new-version }}."

      - name: Auto-merge PR when checks pass
        if: steps.create-pr.outputs.pull-request-operation == 'created'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.token }}
          pull-request-number: ${{ steps.create-pr.outputs.pull-request-number }}
          merge-method: squash
