name: Release Docker Image

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      registry_url:
        required: true
        type: string
      image_name:
        type: string
        default: ${{ github.repository }}
      dockerfile:
        type: string
        default: ./Dockerfile
      context:
        type: string
        default: .
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: read
      attestations: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to ${{ inputs.registry_url }}
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ${{ inputs.registry_url }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@dbef88086f6cef02e264edb7dbf63250c17cef6c # v5.5.0
        with:
          images: ${{ inputs.registry_url }}/${{ inputs.image_name }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ inputs.registry_url }}/${{ inputs.image_name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
