name: Release Docker Image

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      registry_url:
        required: true
        type: string
      image_name:
        type: string
        default: ${{ github.repository }}
      dockerfile:
        type: string
        default: ./Dockerfile
      context:
        type: string
        default: .
      cache:
        type: boolean
        default: false
      cache_registry:
        type: string
        default: ""
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: read
      attestations: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get current version tag
        id: get_version
        run: |
          version=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          if [ -z "$version" ]; then
            echo "No version tag found. Exiting."
            exit 1
          fi
          echo "version=$version" >> $GITHUB_ENV

      - name: Build and push
        id: push
        uses: aevea/action-kaniko@master
        with:
          registry: ${{ inputs.registry_url }}
          image: ${{ inputs.image_name }}
          tag: ${{ env.version }}
          tag_with_latest: true
          build_file: ${{ inputs.dockerfile }}
          path: ${{ inputs.context }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}
          cache: ${{ inputs.cache }}
          cache_registry: ${{ inputs.cache_registry }}
