name: Release Docker Image

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      registry_url:
        required: true
        type: string
      image_name:
        type: string
        default: ${{ github.repository }}
      dockerfile:
        type: string
        default: ./Dockerfile
      context:
        type: string
        default: .
      cache:
        type: boolean
        default: false
      cache_registry:
        type: string
        default: ""
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: read
      attestations: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Get current version tag
        id: get_version
        run: |
          version=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
          if [ -z "$version" ]; then
            echo "No version tag found. Exiting."
            exit 1
          fi
          echo "version=$version" >> $GITHUB_ENV

      - name: Build Docker image
      uses: ./.github/workflows/kaniko.yaml
      with:
          registry_url: ${{ inputs.registry_url }}
          image_name: ${{ inputs.image_name }}
          dockerfile: ${{ inputs.dockerfile }}
          context: ${{ inputs.context }}
          cache: ${{ inputs.cache }}
          cache_registry: ${{ inputs.cache_registry }}
          image_push: true
          tag: ${{ env.version }}
          registry_username: ${{ secrets.registry_username }}
          registry_password: ${{ secrets.registry_password }}
